animals_species:
    resource: "@AnimalsBundle/Controller/SpeciesController.php"
    type:     annotation

work_time_work_time:
    resource: "@WorkTimeBundle/Controller/WorkTimeController.php"
    type:     annotation

animals_animals:
    resource: "@AnimalsBundle/Controller/AnimalsController.php"
    type:     annotation

animals_breed:
    resource: "@AnimalsBundle/Controller/BreedController.php"
    type:     annotation

#work_time:
#    resource: "@WorkTimeBundle/Controller/"
#    type:     annotation
#    prefix:   /

#animals:
#    resource: "@AnimalsBundle/Controller/"
#    type:     annotation
#    prefix:   /

user_default:
    resource: "@UserBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

user_users:
    resource: "@UserBundle/Controller/UsersController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"