<?php

namespace CrmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VisitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitsRepository extends EntityRepository
{
}
